{{- if and .Values.rbac.create .Values.rbac.clusterWide }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubectl-ai.fullname" . }}-binding
  labels:
    {{- include "kubectl-ai.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubectl-ai.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubectl-ai.fullname" . }}-role
{{- end }}


